# Generated by Django 3.0.7 on 2021-04-15 11:57

from django.db import migrations, models
import django.db.models.deletion
import mailer.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mailinglist', '0003_auto_20200423_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], max_length=8)),
                ('time_taken_ms', models.PositiveIntegerField(null=True)),
                ('recipients', models.ManyToManyField(to='mailinglist.Subscription')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('type', models.CharField(choices=[('marketing_email', 'Marketing email'), ('transactional_email', 'Transactional email')], max_length=20)),
                ('subject', models.CharField(max_length=100, validators=[mailer.validators.validate_template_variables, mailer.validators.validate_no_html])),
                ('content_plain', models.TextField(blank=True, validators=[mailer.validators.validate_template_variables, mailer.validators.validate_no_html])),
                ('content_html', models.TextField(blank=True, validators=[mailer.validators.validate_template_variables, mailer.validators.validate_html], verbose_name='content HTML')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('type', models.CharField(choices=[('link', 'Link'), ('image', 'Image'), ('pixel', 'Pixel')], max_length=5)),
                ('url', models.CharField(max_length=500)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailer.Job')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrackerEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailinglist.Subscription')),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailer.Tracker')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('subject', models.CharField(max_length=100)),
                ('content_plain', models.TextField(blank=True)),
                ('content_html', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], max_length=8)),
                ('status_message', models.CharField(max_length=200)),
                ('time_taken_ms', models.PositiveIntegerField(null=True)),
                ('job', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='mailer.Job')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mailinglist.Subscription')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='job',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mailer.Template'),
        ),
    ]
