# Generated by Django 3.0.4 on 2020-03-28 15:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('created_at', models.DateTimeField(blank=True, db_index=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
