# Generated by Django 3.0.4 on 2020-04-12 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailinglist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='subscription',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='subscription',
            name='ip',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='subscription',
            name='language',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='subscription',
            name='region',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
