# Generated by Django 3.0.4 on 2020-04-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailinglist', '0002_auto_20200412_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='campaign',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='subscription',
            name='landing_page',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='subscription',
            name='medium',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='subscription',
            name='source',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
