# Generated by Django 3.0.7 on 2021-08-16 20:41

from django.db import migrations, models
import django.db.models.deletion
import mailinglist.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mailinglist', '0003_auto_20200423_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='token',
            field=models.CharField(default=mailinglist.models.generate_token, help_text='Lets user update their preferences if they have this token. Prevents mallicious attempts at changing users preferences.', max_length=64),
        ),
        migrations.AddField(
            model_name='subscription',
            name='unsubscribed_from_all_lists',
            field=models.BooleanField(default=False, help_text='If the user has chosen to unsubscribe from all lists'),
        ),
        migrations.CreateModel(
            name='ListUnsubscribes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True, db_index=True)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailinglist.List')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailinglist.Subscription')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='unsubscribes',
            field=models.ManyToManyField(help_text='Which lists the user has unsubscribed from', through='mailinglist.ListUnsubscribes', to='mailinglist.List'),
        ),
    ]
