# Generated by Django 3.0.7 on 2021-08-16 20:57

from django.db import migrations

from mailinglist.models import generate_token



def forwards_func(apps, schema_editor):
    Subscription = apps.get_model('mailinglist', 'Subscription')
    for subscription in Subscription.objects.all():
        subscription.token = generate_token()
        subscription.save()

def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('mailinglist', '0004_auto_20210816_2141'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]


