# Generated by Django 3.0.4 on 2020-03-28 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, db_index=True)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('content', models.TextField()),
                ('photo', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post', to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
