# Generated by Django 3.0.7 on 2021-05-04 08:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, db_index=True)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('question', models.TextField(help_text='Question people asked.', verbose_name='Question')),
                ('answer', models.TextField(blank=True, help_text='Answer of the question.', null=True, verbose_name='Answer')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
