# Generated by Django 3.0.7 on 2021-05-05 21:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, db_index=True)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('title', models.CharField(help_text='Question asked', max_length=200, verbose_name='Question')),
                ('answer', models.TextField(blank=True, help_text='Answer to the question', null=True, verbose_name='Answer')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
