# Generated by Django 3.0.7 on 2021-05-04 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0001_create_faq_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FAQ',
            new_name='Question',
        ),
    ]
